//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b_KnowLedge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasesDados
    {
        public string StampBaseDados { get; set; }
        public string StampProjeto { get; set; }
        public string Servername { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Initialcatalog { get; set; }
        public Nullable<bool> Encrypt { get; set; }
        public Nullable<bool> Trustservercertificate { get; set; }
        public string Ousrinis { get; set; }
        public Nullable<System.DateTime> Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public Nullable<System.DateTime> Usrdata { get; set; }
        public string Usrhora { get; set; }
        public Nullable<System.DateTime> DataSincronizacao { get; set; }
    
        public virtual Projetos Projetos { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
        public virtual Utilizadores Utilizadores1 { get; set; }
    }
}
