//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b_KnowLedge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtipos
    {
        public Subtipos()
        {
            this.Tabelas = new HashSet<Tabelas>();
        }
    
        public string StampSubtipo { get; set; }
        public string StampTipo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Ousrinis { get; set; }
        public Nullable<System.DateTime> Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public Nullable<System.DateTime> Usrdata { get; set; }
        public string Usrhora { get; set; }
        public Nullable<System.DateTime> DataSincronizacao { get; set; }
    
        public virtual Tipos Tipos { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
        public virtual Utilizadores Utilizadores1 { get; set; }
        public virtual ICollection<Tabelas> Tabelas { get; set; }
    }
}
