//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b_KnowLedge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizadores
    {
        public Utilizadores()
        {
            this.Anexos = new HashSet<Anexos>();
            this.Anexos1 = new HashSet<Anexos>();
            this.BasesDados = new HashSet<BasesDados>();
            this.BasesDados1 = new HashSet<BasesDados>();
            this.Conhecimentos = new HashSet<Conhecimentos>();
            this.Conhecimentos1 = new HashSet<Conhecimentos>();
            this.Entidades = new HashSet<Entidades>();
            this.Entidades1 = new HashSet<Entidades>();
            this.Pessoas = new HashSet<Pessoas>();
            this.Pessoas1 = new HashSet<Pessoas>();
            this.Projetos = new HashSet<Projetos>();
            this.Projetos1 = new HashSet<Projetos>();
            this.Subtipos = new HashSet<Subtipos>();
            this.Subtipos1 = new HashSet<Subtipos>();
            this.Tabelas = new HashSet<Tabelas>();
            this.Tabelas1 = new HashSet<Tabelas>();
            this.Tipos = new HashSet<Tipos>();
            this.Tipos1 = new HashSet<Tipos>();
        }
    
        public string StampUtilizador { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public string CodPostal { get; set; }
        public string Telemovel { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public byte[] Foto { get; set; }
        public string Ousrinis { get; set; }
        public Nullable<System.DateTime> Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public Nullable<System.DateTime> Usrdata { get; set; }
        public string Usrhora { get; set; }
        public Nullable<System.DateTime> DataSincronizacao { get; set; }
    
        public virtual ICollection<Anexos> Anexos { get; set; }
        public virtual ICollection<Anexos> Anexos1 { get; set; }
        public virtual ICollection<BasesDados> BasesDados { get; set; }
        public virtual ICollection<BasesDados> BasesDados1 { get; set; }
        public virtual ICollection<Conhecimentos> Conhecimentos { get; set; }
        public virtual ICollection<Conhecimentos> Conhecimentos1 { get; set; }
        public virtual ICollection<Entidades> Entidades { get; set; }
        public virtual ICollection<Entidades> Entidades1 { get; set; }
        public virtual ICollection<Pessoas> Pessoas { get; set; }
        public virtual ICollection<Pessoas> Pessoas1 { get; set; }
        public virtual ICollection<Projetos> Projetos { get; set; }
        public virtual ICollection<Projetos> Projetos1 { get; set; }
        public virtual ICollection<Subtipos> Subtipos { get; set; }
        public virtual ICollection<Subtipos> Subtipos1 { get; set; }
        public virtual ICollection<Tabelas> Tabelas { get; set; }
        public virtual ICollection<Tabelas> Tabelas1 { get; set; }
        public virtual ICollection<Tipos> Tipos { get; set; }
        public virtual ICollection<Tipos> Tipos1 { get; set; }
    }
}
